#!/usr/bin/env bash
# ===========================================================================
# AIOX Studio — TurboQuant Setup Script
#
# Compiles a llama.cpp fork with TurboQuant KV cache compression support.
# This enables 3.25-4.25 bit KV cache quantization via Walsh-Hadamard
# Transform + PolarQuant, allowing larger models (14B→32B) with longer
# context (4K→32K+) on Apple Silicon.
#
# Usage:
#   bash scripts/setup_turboquant.sh [--clean] [--test]
#
# Requirements:
#   - macOS with Apple Silicon (M1/M2/M3/M4)
#   - Xcode Command Line Tools
#   - cmake >= 3.20
#   - A GGUF model file for testing
# ===========================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TURBO_DIR="${PROJECT_ROOT}/.turbo"
LLAMA_DIR="${TURBO_DIR}/llama-cpp-turboquant"
BUILD_DIR="${LLAMA_DIR}/build"
SERVER_BIN="${BUILD_DIR}/bin/llama-server"
CONFIG_FILE="${TURBO_DIR}/turbo.env"
TURBO_PORT="${AIOX_TURBO_PORT:-8081}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${CYAN}[turbo]${NC} $1"; }
ok()   { echo -e "${GREEN}[turbo] ✓${NC} $1"; }
warn() { echo -e "${YELLOW}[turbo] ⚠${NC} $1"; }
fail() { echo -e "${RED}[turbo] ✗${NC} $1"; exit 1; }

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------

check_prerequisites() {
    log "Verificando pré-requisitos..."

    if [[ "$(uname -s)" != "Darwin" ]]; then
        fail "TurboQuant Metal kernels requerem macOS."
    fi

    if [[ "$(uname -m)" != "arm64" ]]; then
        warn "Esperado Apple Silicon (arm64). Compilação pode funcionar, mas sem Metal otimizado."
    fi

    command -v cmake >/dev/null 2>&1 || fail "cmake não encontrado. Instale via: brew install cmake"
    command -v git >/dev/null 2>&1   || fail "git não encontrado."
    command -v make >/dev/null 2>&1  || fail "make não encontrado. Instale Xcode Command Line Tools."

    ok "Pré-requisitos OK"
}

# ---------------------------------------------------------------------------
# Clone / update the turboquant fork
# ---------------------------------------------------------------------------

clone_or_update() {
    mkdir -p "$TURBO_DIR"

    if [[ -d "$LLAMA_DIR/.git" ]]; then
        log "Atualizando llama-cpp-turboquant..."
        cd "$LLAMA_DIR"
        git fetch --depth 1 origin main 2>/dev/null || git fetch --depth 1 origin master 2>/dev/null || true
        git reset --hard FETCH_HEAD 2>/dev/null || true
    else
        log "Clonando llama-cpp-turboquant..."
        # Primary source: community fork with TurboQuant + Metal
        git clone --depth 1 https://github.com/DanielBBrasileiro/turboquant_plus.git "$LLAMA_DIR" 2>/dev/null || {
            # Fallback: try alternate fork
            warn "Primary clone failed, trying upstream llama.cpp..."
            git clone --depth 1 https://github.com/ggerganov/llama.cpp.git "$LLAMA_DIR" 2>/dev/null || {
                fail "Não foi possível clonar o repositório."
            }
        }
    fi

    ok "Repositório pronto em $LLAMA_DIR"
}

# ---------------------------------------------------------------------------
# Compile with Metal support
# ---------------------------------------------------------------------------

compile() {
    log "Compilando com Metal (Apple GPU)..."
    cd "$LLAMA_DIR"

    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"

    cmake .. \
        -DGGML_METAL=ON \
        -DGGML_METAL_EMBED_LIBRARY=ON \
        -DLLAMA_BUILD_SERVER=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_OSX_ARCHITECTURES=arm64 \
        2>&1 | tail -5

    cmake --build . --config Release -j "$(sysctl -n hw.logicalcpu)" 2>&1 | tail -10

    if [[ ! -f "$SERVER_BIN" ]]; then
        fail "Compilação falhou: $SERVER_BIN não encontrado"
    fi

    ok "Compilação concluída: $SERVER_BIN"
    echo "   Tamanho: $(du -h "$SERVER_BIN" | cut -f1)"
}

# ---------------------------------------------------------------------------
# Write configuration
# ---------------------------------------------------------------------------

write_config() {
    log "Escrevendo configuração..."

    cat > "$CONFIG_FILE" << EOF
# AIOX TurboQuant Configuration
# Generated by setup_turboquant.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

AIOX_TURBO_SERVER_BIN=${SERVER_BIN}
AIOX_TURBO_PORT=${TURBO_PORT}
AIOX_TURBO_URL=http://127.0.0.1:${TURBO_PORT}

# KV Cache Compression Presets
# turbo3: ~3.25 bits/value (4.9x compression) — best for long context
# turbo4: ~4.25 bits/value (3.8x compression) — best balance quality/efficiency
AIOX_TURBO_CACHE_TYPE_K=q8_0
AIOX_TURBO_CACHE_TYPE_V=turbo4
AIOX_TURBO_FLASH_ATTENTION=1
AIOX_TURBO_CONTEXT_LENGTH=32768
AIOX_TURBO_GPU_LAYERS=99

# Status
AIOX_TURBO_INSTALLED=true
AIOX_TURBO_INSTALLED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

    ok "Configuração salva em $CONFIG_FILE"
}

# ---------------------------------------------------------------------------
# Test the server
# ---------------------------------------------------------------------------

run_test() {
    log "Testando servidor TurboQuant..."

    # Check if any GGUF models exist in common locations
    local test_model=""
    for candidate in \
        "$HOME/.ollama/models/"*.gguf \
        "$HOME/models/"*.gguf \
        "$TURBO_DIR/"*.gguf; do
        if [[ -f "$candidate" ]]; then
            test_model="$candidate"
            break
        fi
    done

    if [[ -z "$test_model" ]]; then
        warn "Nenhum modelo GGUF encontrado para teste."
        warn "Para testar manualmente:"
        echo ""
        echo "  $SERVER_BIN \\"
        echo "    -m /path/to/model.gguf \\"
        echo "    --cache-type-k q8_0 \\"
        echo "    --cache-type-v turbo4 \\"
        echo "    -fa 1 \\"
        echo "    --port $TURBO_PORT \\"
        echo "    -ngl 99"
        echo ""
        return 0
    fi

    log "Usando modelo de teste: $(basename "$test_model")"

    # Start server in background
    "$SERVER_BIN" \
        -m "$test_model" \
        --cache-type-k q8_0 \
        --cache-type-v turbo4 \
        -fa 1 \
        --port "$TURBO_PORT" \
        -ngl 99 \
        > /dev/null 2>&1 &
    local server_pid=$!

    sleep 3

    # Health check
    if curl -s "http://127.0.0.1:${TURBO_PORT}/health" | grep -q '"status"'; then
        ok "Servidor respondendo em http://127.0.0.1:${TURBO_PORT}"
    else
        warn "Servidor não respondeu ao health check"
    fi

    # Cleanup
    kill "$server_pid" 2>/dev/null || true
    wait "$server_pid" 2>/dev/null || true

    ok "Teste concluído"
}

# ---------------------------------------------------------------------------
# Clean install
# ---------------------------------------------------------------------------

clean() {
    log "Limpando instalação anterior..."
    rm -rf "$TURBO_DIR"
    ok "Diretório .turbo removido"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    echo ""
    echo -e "${CYAN}╔═══════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}  🚀 AIOX Studio — TurboQuant KV Cache Setup          ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}  Compressão 3.8-4.9x do KV Cache via PolarQuant      ${CYAN}║${NC}"
    echo -e "${CYAN}╚═══════════════════════════════════════════════════════╝${NC}"
    echo ""

    local do_test=false
    for arg in "$@"; do
        case "$arg" in
            --clean) clean; exit 0 ;;
            --test)  do_test=true ;;
            --help)
                echo "Usage: bash scripts/setup_turboquant.sh [--clean] [--test]"
                echo ""
                echo "Options:"
                echo "  --clean   Remove .turbo directory and exit"
                echo "  --test    Run health check after compilation"
                exit 0
                ;;
        esac
    done

    check_prerequisites
    clone_or_update
    compile
    write_config

    if $do_test; then
        run_test
    fi

    echo ""
    ok "Setup completo!"
    echo ""
    echo -e "  Próximos passos:"
    echo -e "  1. Baixe um modelo GGUF (ex: qwen2.5-14b-instruct-q4_K_M.gguf)"
    echo -e "  2. Configure AIOX_TURBO_MODEL_PATH no .env"
    echo -e "  3. Use: python3 aiox.py doctor   (verifica health)"
    echo -e "  4. Use: AIOX_MODEL_PROFILE=turbo python3 aiox.py agent \"sua ideia\""
    echo ""
}

main "$@"
