"""
AIOX PDF Generator — v4.4
===========================
Gera documentos PDF multi-página de alta qualidade.
Formatos: narrativa cinematográfica, apresentação de projeto, post multi-frame.

Usage standalone:
    python3 core/generators/pdf_generator.py \\
        --brief briefings/presentation.yaml \\
        --output output/pdf/presentation.pdf

Uso via orchestrator: quando output.formats inclui "pdf".
"""
import json
from pathlib import Path
from typing import List, Optional

ROOT = Path(__file__).resolve().parent.parent.parent


def _load_tokens() -> dict:
    token_path = ROOT / "assets/brand/tokens.json"
    if token_path.exists():
        with open(token_path) as f:
            return json.load(f)
    return {}


def _require_reportlab():
    try:
        from reportlab.pdfgen import canvas as rl_canvas
        from reportlab.lib.units import mm
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.colors import HexColor, white, black
        return rl_canvas, mm, A4, HexColor, white, black
    except ImportError:
        raise ImportError(
            "reportlab não instalado. Execute: pip install reportlab"
        )


def _hex_to_reportlab(hex_color: str):
    rl_canvas, _, _, HexColor, white, black = _require_reportlab()
    clean = hex_color.strip().lstrip("#")
    if len(clean) == 6:
        return HexColor(f"#{clean}")
    return white


def generate_from_frames(
    frame_paths: List[str],
    output_pdf: str,
    title: str = "AIOX",
    brief: dict = None,
    page_size: tuple = None,
) -> str:
    """
    Gera PDF com uma imagem por página a partir de uma lista de frames PNG.

    Args:
        frame_paths: Lista de caminhos PNG/JPG.
        output_pdf:  Caminho de saída .pdf.
        title:       Título do documento (nos metadados).
        brief:       Dict do briefing para tokens e metadados.
        page_size:   (width_pt, height_pt) — default: 1080x1920 em pontos.
    Returns:
        Caminho do PDF gerado.
    """
    rl_canvas, mm, A4, HexColor, white, black = _require_reportlab()

    tokens = _load_tokens()
    bg_hex = tokens.get("brand", {}).get("color_states", {}).get("dark", {}).get("background", "#000000")
    bg_color = _hex_to_reportlab(bg_hex)

    # Dimensões: 1pt = 1/72 inch. 1080px @ 72dpi = 1080pt
    if page_size is None:
        fmt = (brief or {}).get("meta", {}).get("format", "vertical_9_16") if brief else "vertical_9_16"
        sizes = {
            "vertical_9_16": (1080, 1920),
            "square_1_1": (1080, 1080),
            "wide_16_9": (1920, 1080),
            "instagram_post": (1080, 1080),
            "linkedin_post": (1200, 627),
        }
        pw, ph = sizes.get(fmt, (1080, 1920))
        # Escala para caber em A4 preservando aspect ratio (opcional)
        # Mantemos em px/pt para fidelidade máxima
        page_size = (pw, ph)

    out_path = Path(output_pdf)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    c = rl_canvas.Canvas(str(out_path), pagesize=page_size)
    c.setTitle(title)
    c.setAuthor("AIOX Studio")
    c.setSubject(f"Generated by AIOX Limitless Engine v4.4")

    pw, ph = page_size

    for i, frame_path in enumerate(frame_paths):
        fp = Path(frame_path)
        if not fp.exists():
            print(f"  ⚠️  Frame não encontrado: {frame_path}")
            c.showPage()
            continue

        # Background preto total antes da imagem
        c.setFillColor(bg_color)
        c.rect(0, 0, pw, ph, fill=1, stroke=0)

        # Imagem centralizada com cover fit
        try:
            from PIL import Image
            img = Image.open(frame_path)
            iw, ih = img.size
            scale = min(pw / iw, ph / ih)
            nw, nh = iw * scale, ih * scale
            x = (pw - nw) / 2
            y = (ph - nh) / 2
            c.drawImage(frame_path, x, y, width=nw, height=nh, preserveAspectRatio=True)
        except ImportError:
            # Fallback sem Pillow: imagem sem cálculo de fit
            c.drawImage(frame_path, 0, 0, width=pw, height=ph)

        # Grain overlay via transparência (visual)
        grain = tokens.get("brand", {}).get("materials", {}).get("grain", 0.06)
        c.setFillAlpha(grain * 0.5)
        c.setFillColor(white)
        c.rect(0, 0, pw, ph, fill=1, stroke=0)
        c.setFillAlpha(1.0)

        print(f"  📄 Página {i+1}/{len(frame_paths)} → {fp.name}")
        c.showPage()

    c.save()
    print(f"✅ PDF gerado → {out_path} ({len(frame_paths)} páginas)")
    return str(out_path)


def generate_narrative_pdf(
    brief_path: str,
    frame_paths: List[str] = None,
    output_pdf: str = None,
) -> str:
    """
    Gera PDF narrativo a partir de um briefing.
    Se frame_paths não fornecido, usa frames em output/frames/ automaticamente.
    """
    import yaml
    with open(brief_path) as f:
        brief = yaml.safe_load(f)

    title = brief.get("meta", {}).get("title", "AIOX Narrative")
    safe = title.lower().replace(" ", "_")[:40]

    if frame_paths is None:
        frames_dir = ROOT / "output" / "frames"
        if frames_dir.exists():
            frame_paths = sorted([str(p) for p in frames_dir.glob("*.png")])
        else:
            print("⚠️  Nenhum frame encontrado. Execute a extração de frames primeiro.")
            return ""

    if not frame_paths:
        print("⚠️  Lista de frames vazia.")
        return ""

    if output_pdf is None:
        output_pdf = str(ROOT / "output" / "pdf" / f"{safe}.pdf")

    return generate_from_frames(frame_paths, output_pdf, title=title, brief=brief)


def generate_carousel_pdf(
    carousel_dir: str,
    output_pdf: str,
    title: str = "AIOX Carousel",
) -> str:
    """
    Converte um carrossel gerado pelo carousel_generator em PDF.
    """
    car_dir = Path(carousel_dir)
    frames = sorted([str(p) for p in car_dir.glob("slide_*.jpeg")] +
                    [str(p) for p in car_dir.glob("slide_*.jpg")] +
                    [str(p) for p in car_dir.glob("slide_*.png")])

    if not frames:
        print(f"⚠️  Nenhum slide encontrado em {carousel_dir}")
        return ""

    # Lê metadata do carrossel se disponível
    manifest_path = car_dir / "manifest.json"
    if manifest_path.exists():
        with open(manifest_path) as f:
            manifest = json.load(f)
        dims = manifest.get("dimensions", "1080x1080").split("x")
        page_size = (int(dims[0]), int(dims[1]))
    else:
        page_size = (1080, 1080)

    print(f"📚 Gerando PDF do carrossel ({len(frames)} slides)...")
    return generate_from_frames(frames, output_pdf, title=title, page_size=page_size)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="AIOX PDF Generator")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--brief", help="Briefing YAML")
    group.add_argument("--carousel", help="Diretório de carrossel")
    group.add_argument("--frames", nargs="+", help="Lista de frames PNG/JPG")
    parser.add_argument("--output", help="Caminho do PDF de saída")
    parser.add_argument("--title", default="AIOX")
    args = parser.parse_args()

    if args.brief:
        generate_narrative_pdf(args.brief, output_pdf=args.output)
    elif args.carousel:
        out = args.output or "output/pdf/carousel.pdf"
        generate_carousel_pdf(args.carousel, out, title=args.title)
    elif args.frames:
        out = args.output or "output/pdf/frames.pdf"
        generate_from_frames(args.frames, out, title=args.title)
